
<link href="<?php echo $this->basePath('assets/global/plugins/bootstrap-daterangepicker/daterangepicker-bs3.css')?>" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->basePath('assets/global/plugins/bootstrap-datepicker/css/bootstrap-datepicker3.min.css')?>" rel="stylesheet" type="text/css" />

<script src="<?php echo $this->basePath('assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js')?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/global/plugins/bootstrap-daterangepicker/moment.min.js')?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js')?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/global/plugins/bootstrap-daterangepicker/daterangepicker.js')?>" type="text/javascript"></script>

<script src="<?php echo $this->basePath('assets/global/plugins/morris/morris.min.js');?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/global/plugins/morris/raphael-min.js');?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/global/plugins/counterup/jquery.waypoints.min.js');?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/global/plugins/counterup/jquery.counterup.min.js');?>" type="text/javascript"></script>

<script src="<?php echo $this->basePath('assets/global/plugins/bootstrap/js/bootstrap.min.js');?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/global/plugins/js.cookie.min.js" type="text/javascript');?>"></script>
<script src="<?php echo $this->basePath('assets/global/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js');?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js');?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/global/plugins/jquery.blockui.min.js" type="text/javascript');?>"></script>
<script src="<?php echo $this->basePath('assets/global/plugins/uniform/jquery.uniform.min.js');?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js');?>" type="text/javascript"></script>
<!-- END CORE PLUGINS -->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script src="<?php echo $this->basePath('assets/global/scripts/datatable.js');?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/global/plugins/datatables/datatables.min.js');?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js');?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js');?>" type="text/javascript"></script>
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN THEME GLOBAL SCRIPTS -->
<script src="<?php echo $this->basePath('assets/global/scripts/app.min.js');?>" type="text/javascript"></script>
<!-- END THEME GLOBAL SCRIPTS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->


<script src="<?php echo $this->basePath('assets/pages/scripts/dashboard.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/pages/scripts/components-date-time-pickers.min.js')?>" type="text/javascript"></script>

<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/chosen/1.4.2/chosen.min.css">
<script src="//cdnjs.cloudflare.com/ajax/libs/chosen/1.4.2/chosen.jquery.min.js"></script>


<div class="row">
	<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
		<div class="dashboard-stat blue">
			<div class="visual">
				<i class="fa fa-tasks"></i>
			</div>
			<div class="details">
				<div class="number">
					<span data-counter="counterup" data-value="0" id="manifestacoes-total">0</span>
				</div>
				<div class="desc"> Eventos </div>
			</div>
			<a class="more" href="javascript:;">
				&nbsp;&nbsp;
			</a>
		</div>
	</div>
</div>
<!-- BEGIN PAGE BASE CONTENT -->
<div class="row">
	<div class="col-md-12">

		<!-- Begin: life time stats -->
		<div class="portlet light portlet-fit portlet-datatable bordered">
			<div class="portlet-title">
				<div class="caption">
					<i class="icon-settings font-dark"></i>
					<span class="caption-subject font-dark sbold uppercase">Detalhe Evento Pendente</span>
				</div>
				<div class="actions">
					<div class="btn-group">
						<a class="btn red btn-outline btn-circle" href="javascript:;" data-toggle="dropdown" aria-expanded="false">
							<i class="fa fa-share"></i>
							<span class="hidden-xs"> Exportar CSV </span>
						</a>
					</div>
				</div>
			</div>
			<div class="portlet-body">

				<div class="table-container">
					<table class="table table-striped table-bordered table-hover table-checkable" id="datatable_ajax">
						<thead>
						<tr role="row" class="heading">
							<th> # </th>
							<th> Data Coleta</th>
							<th> Data Previsão </th>
							<th> Data Transferência</th>
							<th> Tempo horas Previsto</th>
							<th> Tempo Horas Decorrido</th>
							<th> Evento</th>
							<th> Urgente</th>
							<th> Mensagem</th>
							<th> Agente From</th>
							<th> Nome consumidor</th>

						</tr>
						<tr role="row" class="filter hidden">
							<td>
								<div class="hidden">
									<div class="margin-bottom-5">
										<button class="btn btn-sm green btn-outline filter-submit margin-bottom" id="submit-filter">
											<i class="fa fa-search"></i> Search
										</button>
									</div>
									<button class="btn btn-sm red btn-outline filter-cancel">
										<i class="fa fa-times"></i> Reset
									</button>

								</div>
								<input type="hidden" class="form-control form-filter input-sm form-filter-pessoa" id="dia-ini" name="depto_destino" value="<?php echo $data['depto_destino']?>">
								<input type="hidden" class="form-control form-filter input-sm form-filter-pessoa" id="dia-ini" name="agente_to" value="<?php echo $data['agente_to']?>">
								<input type="hidden" class="form-control form-filter input-sm form-filter-pessoa" id="dia-ini" name="evento" value="<?php echo $data['evento']?>">
							</td>
							<td>

							</td>
							<td>

							</td>
							<td>

							</td>
							<td>

							</td>
							<td>

							</td>
							<td>

							</td>
							<td>

							</td>
							<td>

							</td>

							<td>

							</td>
							<td>

							</td>

						</tr>
						</thead>
						<tbody> </tbody>
					</table>
				</div>
			</div>
		</div>
		<!-- End: life time stats -->
	</div>
</div>
<div class="modal fade" id="basic" tabindex="-1" role="basic" aria-hidden="true" style="display: none;">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
				<h4 class="modal-title">Orientação</h4>
			</div>
			<div class="modal-body">
				<p id="id-text">

				</p>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn dark btn-outline" data-dismiss="modal" onclick="$('#id-text').empty()">Fechar</button>
			</div>
		</div>
		<!-- /.modal-content -->
	</div>
	<!-- /.modal-dialog -->
</div>


<script>
	function passaValorHidden(element1,element2){
		element2.val(element1.val());
	}

	var TableDatatablesAjax = function () {

		var initPickers = function () {
			//init date pickers
			$('.date-picker').datepicker({
				rtl: App.isRTL(),
				autoclose: true
			});
		}

		var handleRecords = function () {

			var grid = new Datatable();

			grid.init({
				src: $("#datatable_ajax"),


				onSuccess: function (grid, response) {

					$('#manifestacoes-total').attr('data-value',response.recordsTotal);
					$('#manifestacoes-total').counterUp({time: 2500});

					// grid:        grid object
					// response:    json object of server side ajax response
					// execute some code after table records loaded
				},
				onError: function (grid) {
					// execute some code on network or other general error
				},
				onDataLoad: function(grid) {
					// execute some code on ajax data load
				},
				loadingMessage: 'Carregando...',
				dataTable: { // here you can define a typical datatable settings from http://datatables.net/usage/options

					// Uncomment below line("dom" parameter) to fix the dropdown overflow issue in the datatable cells. The default datatable layout
					// setup uses scrollable div(table-scrollable) with overflow:auto to enable vertical scroll(see: assets/global/scripts/datatable.js).
					// So when dropdowns used the scrollable div should be removed.
					//"dom": "<'row'<'col-md-8 col-sm-12'pli><'col-md-4 col-sm-12'<'table-group-actions pull-right'>>r>t<'row'<'col-md-8 col-sm-12'pli><'col-md-4 col-sm-12'>>",

					"bStateSave": true, // save datatable state(pagination, sort, etc) in cookie.
//                    paging: false,
					searching: false,
					"lengthMenu": [
						[10, 20, 50, 100, 150],
						[10, 20, 50, 100, 150] // change per page values here
					],
					"pageLength": 10, // default record count per page
					"ajax": {
						"url": "<?php echo $this->basePath('relatorio/list-detalhe-evento'); ?>", // ajax source
					},
					"order": [
						[1, "asc"]
					],// set first column as a default sort by asc
					columnDefs: [ { orderable: false, targets: [0] }, ],
				}
			});

			// handle group actionsubmit button click
			grid.getTableWrapper().on('click', '.table-group-action-submit', function (e) {
				e.preventDefault();
				var action = $(".table-group-action-input", grid.getTableWrapper());
				if (action.val() != "" && grid.getSelectedRowsCount() > 0) {
					grid.setAjaxParam("customActionType", "group_action");
					grid.setAjaxParam("customActionName", action.val());
					grid.setAjaxParam("id", grid.getSelectedRows());
					grid.getDataTable().ajax.reload();
					grid.clearAjaxParams();
				} else if (action.val() == "") {
					App.alert({
						type: 'danger',
						icon: 'warning',
						message: 'Please select an action',
						container: grid.getTableWrapper(),
						place: 'prepend'
					});
				} else if (grid.getSelectedRowsCount() === 0) {
					App.alert({
						type: 'danger',
						icon: 'warning',
						message: 'No record selected',
						container: grid.getTableWrapper(),
						place: 'prepend'
					});
				}
			});
		}

		return {

			//main function to initiate the module
			init: function () {

				initPickers();
				handleRecords();
			}

		};

	}();

	jQuery(document).ready(function() {
		TableDatatablesAjax.init();
		$('select').chosen({
			no_results_text: "Oops, Não encontramos nada!"
		});
		$('select[name="datatable_ajax_length"').chosen('destroy');
		$('#submit-filter').click();
	});

</script>

<style>
	.chosen-container{
		width:100% !important;
	}
</style>