<script src="https://code.highcharts.com/highcharts.js"></script>
<script src="https://code.highcharts.com/modules/exporting.js"></script>

<div id="container" style="min-width: 310px; height: 400px; margin: 0 auto"></div>

<script>
	$(function () {
        $('#container').highcharts({
            chart: {
                type: 'area'
            },
            title: {
                text: 'Entrada de Contato'
            },
            subtitle: {
                text: ''
            },
            xAxis: {
                categories: [<?php  echo $this->manifestacao()->createArrayGraphicEnt()?>],
                tickmarkPlacement: 'on',
                title: {
                    enabled: false
                }
            },
            yAxis: {
                title: {
                    text: 'Qtd'
                },
                labels: {
                    formatter: function () {
                        return this.value ;
                    }
                }
            },
            tooltip: {
                shared: true,
                valueSuffix: ' Qtd'
            },
            plotOptions: {
                area: {
                    stacking: 'normal',
                    lineColor: '#666666',
                    lineWidth: 1,
                    marker: {
                        lineWidth: 1,
                        lineColor: '#666666'
                    }
                }
            },
            series: [{
                name: 'Area Comercial HTH',
                data: [<?php echo $this->manifestacao()->prepareArrayGraphicEnt($areaComercial,7,2016);?>]
            }, {
                name: 'Email Livre',
                data: [<?php echo $this->manifestacao()->prepareArrayGraphicEnt($emailLivre,7,2016);?>]
            }, {
                name: 'Fale Conosco',
                data: [<?php echo $this->manifestacao()->prepareArrayGraphicEnt($faleConosco,7,2016);?>]
            }, {
                name: 'Telefone',
                data: [<?php echo $this->manifestacao()->prepareArrayGraphicEnt($telefone,7,2016);?>]
            },]
        });
    });
</script>
