
<link href="<?php echo $this->basePath('assets/global/plugins/bootstrap-daterangepicker/daterangepicker-bs3.css')?>" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->basePath('assets/global/plugins/bootstrap-datepicker/css/bootstrap-datepicker3.min.css')?>" rel="stylesheet" type="text/css" />

<script src="<?php echo $this->basePath('assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js')?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/global/plugins/bootstrap-daterangepicker/moment.min.js')?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js')?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/global/plugins/bootstrap-daterangepicker/daterangepicker.js')?>" type="text/javascript"></script>

<script src="<?php echo $this->basePath('assets/global/plugins/morris/morris.min.js');?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/global/plugins/morris/raphael-min.js');?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/global/plugins/counterup/jquery.waypoints.min.js');?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/global/plugins/counterup/jquery.counterup.min.js');?>" type="text/javascript"></script>

<script src="<?php echo $this->basePath('assets/global/plugins/bootstrap/js/bootstrap.min.js');?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/global/plugins/js.cookie.min.js" type="text/javascript');?>"></script>
<script src="<?php echo $this->basePath('assets/global/plugins/bootstrap-hover-dropdown/bootstrap-hover-dropdown.min.js');?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/global/plugins/jquery-slimscroll/jquery.slimscroll.min.js');?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/global/plugins/jquery.blockui.min.js" type="text/javascript');?>"></script>
<script src="<?php echo $this->basePath('assets/global/plugins/uniform/jquery.uniform.min.js');?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/global/plugins/bootstrap-switch/js/bootstrap-switch.min.js');?>" type="text/javascript"></script>
<!-- END CORE PLUGINS -->
<!-- BEGIN PAGE LEVEL PLUGINS -->
<script src="<?php echo $this->basePath('assets/global/scripts/datatable.js');?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/global/plugins/datatables/datatables.min.js');?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/global/plugins/datatables/plugins/bootstrap/datatables.bootstrap.js');?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/global/plugins/bootstrap-datepicker/js/bootstrap-datepicker.min.js');?>" type="text/javascript"></script>
<!-- END PAGE LEVEL PLUGINS -->
<!-- BEGIN THEME GLOBAL SCRIPTS -->
<script src="<?php echo $this->basePath('assets/global/scripts/app.min.js');?>" type="text/javascript"></script>
<!-- END THEME GLOBAL SCRIPTS -->
<!-- BEGIN PAGE LEVEL SCRIPTS -->
	

<script src="<?php echo $this->basePath('assets/pages/scripts/dashboard.min.js'); ?>" type="text/javascript"></script>
<script src="<?php echo $this->basePath('assets/pages/scripts/components-date-time-pickers.min.js')?>" type="text/javascript"></script>

<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/chosen/1.4.2/chosen.min.css">
<script src="//cdnjs.cloudflare.com/ajax/libs/chosen/1.4.2/chosen.jquery.min.js"></script>


<div class="row">
	<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
		<div class="dashboard-stat blue">
			<div class="visual">
				<i class="fa fa-comments"></i>
			</div>
			<div class="details">
				<div class="number">
					<span data-counter="counterup" data-value="0" id="manifestacoes-total">0</span>
				</div>
				<div class="desc"> Total Manifestações</div>
			</div>
			<a class="more" href="javascript:;">
				&nbsp;&nbsp;
			</a>
		</div>
	</div>
	<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
		<div class="dashboard-stat red">
			<div class="visual">
				<i class="fa fa-bar-chart-o"></i>
			</div>
			<div class="details">
				<div class="number">
					<span data-counter="counterup" data-value="0" id="total-contatos">0</span>
				</div>
				<div class="desc"> Total Contatos </div>
			</div>
			<a class="more" href="javascript:;">
					&nbsp;
			</a>
		</div>
	</div>
	<div class="col-lg-4 col-md-4 col-sm-6 col-xs-12">
		<div class="dashboard-stat green">
			<div class="visual">
				<i class="fa fa-shopping-cart"></i>
			</div>
			<div class="details">
				<div class="number">
					<span data-counter="counterup" data-value="0" id="total-consumidores">0</span>
				</div>
				<div class="desc"> Total Consumidores </div>
			</div>
			<a class="more" href="javascript:;" onclick="redirectConsumidores()"> Veja mais
				<i class="m-icon-swapright m-icon-white"></i>
			</a>
		</div>
	</div>
</div>
<!-- BEGIN PAGE BASE CONTENT -->
<div class="row">
	<div class="col-md-12">

		<!-- Begin: life time stats -->
		<div class="portlet light portlet-fit portlet-datatable bordered">
			<div class="portlet-title">
				<div class="caption">
					<i class="icon-settings font-dark"></i>
					<span class="caption-subject font-dark sbold uppercase">Manifestações</span>
				</div>
                <div class="actions">
                    <div class="btn-group">
                        <a class="btn red btn-outline btn-circle" href="javascript:;" data-toggle="dropdown" aria-expanded="false">
                            <i class="fa fa-share"></i>
                            <span class="hidden-xs"> Exportar CSV </span>
                        </a>
                    </div>
                </div>
			</div>
			<div class="portlet-body">

                <div class="row">
                    <div class="col-md-2">
                        <div class="input-group date date-picker margin-bottom-5" data-date-format="dd/mm/yyyy">
                            <input type="text" class="form-control form-filter input-sm" onchange="passaValorHidden($(this),$('#data-ini'))" readonly="" name="order_date_from" placeholder="Data Inicial" value="01/07/2016">
                            <span class="input-group-btn">
                                <button class="btn btn-sm default" type="button">
                                    <i class="fa fa-calendar"></i>
                                </button>
                            </span>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <div class="input-group date date-picker" data-date-format="dd/mm/yyyy">
                            <input type="text" class="form-control form-filter input-sm" readonly=""  onchange="passaValorHidden($(this),$('#data-fim'))" name="order_date_to" placeholder="Data Final" value="31/07/2016">
                            <span class="input-group-btn">
                                <button class="btn btn-sm default" type="button">
                                    <i class="fa fa-calendar"></i>
                                </button>
                            </span>
                        </div>
                    </div>
                    <div class="col-md-2">
                        <button class="btn btn-sm blue" type="button" onclick="$('#submit-filter').click();">OK</button>
                        <a href="javascript:void(0)" class="btn btn-sm red-haze" onclick="showBuscaAvancada()">Busca Avançada</a>
                    </div>
                </div>

                <div class="hidden" id="busca-avancada">
                    <div class="row" style="margin-top: 15px; margin-bottom: 15px">
                         <div class="col-md-3">
                             <input type="text" class="form-control form-filter input-sm" name="order_date_to" placeholder="Palavra do consumidor">
                         </div>
                        <div class="col-md-3">
                            <input type="text" class="form-control form-filter input-sm" name="order_date_to" placeholder="Orientação / Resposta">
                        </div>
                        <div class="col-md-3">
                            <input type="text" class="form-control form-filter input-sm" name="order_date_to" placeholder="Follow-ups">
                        </div>
                    </div>
                </div>

				<div class="table-container">
					<table class="table table-striped table-bordered table-hover table-checkable" id="datatable_ajax">
						<thead>
						<tr role="row" class="heading">

                            <th> # </th>
							<th> Canal </th>
							<th> Man1 </th>
							<th> Man2 </th>
							<th> Man3 </th>
							<th> Categoria </th>
							<th> Cód. Produto </th>
                            <th> Produto </th>
							<th> Grupo </th>
							<th> Família </th>
							<th> Acabamento </th>
							<th> Tipo </th>
                            <th> Cores </th>

						</tr>
						<tr role="row" class="filter">
                            <td>
                                <input type="hidden" class="form-control form-filter input-sm form-filter-pessoa" id="data-ini" name="dataini" value="01/07/2016">
                                <input type="hidden" class="form-control form-filter input-sm form-filter-pessoa" id="data-fim" name="datafim" value="31/07/2016">
                                <input type="hidden" class="form-control form-filter input-sm form-filter-pessoa" id="consumidor" name="consumidor">
                                <input type="hidden" class="form-control form-filter input-sm form-filter-pessoa" id="orientacao" name="orientacao">
                                <input type="hidden" class="form-control form-filter input-sm form-filter-pessoa" id="followups" name="followups">
                                <div class="hidden">
                                    <div class="margin-bottom-5">
                                        <button class="btn btn-sm green btn-outline filter-submit margin-bottom" id="submit-filter">
                                            <i class="fa fa-search"></i> Search</button>
                                    </div>
                                    <button class="btn btn-sm red btn-outline filter-cancel">
                                        <i class="fa fa-times"></i> Reset</button>

                                </div>

                            </td>
							<td>
								<select name="canal[]" class="form-control form-filter input-sm form-filter-consumidor" multiple="true" data-placeholder="Selecionar">
                                    <option value=""></option>
                                    <?php foreach($canal as $value):?>
                                        <option value="<?php  echo $value['canal']?>"><?php  echo $value['canal']?></option>
                                    <?php endforeach;?>
								</select>
							</td>
							<td>
								<select name="man1[]" class="form-control form-filter input-sm form-filter-consumidor" multiple="true" data-placeholder="Selecionar">
                                    <option value=""></option>
                                    <?php foreach($man1 as $value):?>
                                        <option value="<?php  echo $value['man1']?>"><?php  echo $value['man1']?></option>
                                    <?php endforeach;?>
								</select>
							</td>
                            <td>
                                <select name="man2[]" class="form-control form-filter input-sm form-filter-consumidor" multiple="true" data-placeholder="Selecionar">
                                    <option value=""></option>
                                    <?php foreach($man2 as $value):?>
                                        <option value="<?php  echo $value['man2']?>"><?php  echo $value['man2']?></option>
                                    <?php endforeach;?>
                                </select>
                            </td>
							<td>
								<select name="man3[]" class="form-control form-filter input-sm form-filter-consumidor" multiple="true" data-placeholder="Selecionar">
                                    <option value=""></option>
                                    <?php foreach($man3 as $value):?>
                                        <option value="<?php  echo $value['man3']?>"><?php  echo $value['man3']?></option>
                                    <?php endforeach;?>
								</select>
							</td>
                            <td>
                                <select name="grupo[]" class="form-control form-filter input-sm form-filter-consumidor" multiple="true" data-placeholder="Selecionar">
                                    <option value=""></option>
                                    <?php foreach($grupo as $value):?>
                                        <option value="<?php  echo $value['grupo']?>"><?php  echo $value['grupo']?></option>
                                    <?php endforeach;?>

                                </select>
                            </td>
							<td>
								<select name="codProd[]" class="form-control form-filter input-sm form-filter-consumidor" multiple="true" data-placeholder="Selecionar">
                                    <option value=""></option>
                                    <?php foreach($codProd as $value):?>
                                        <option value="<?php  echo $value['codProduto']?>"><?php  echo $value['codProduto']?></option>
                                    <?php endforeach;?>
								</select>
							</td>
							<td>
								<select name="produto[]" class="form-control form-filter input-sm form-filter-consumidor" multiple="true" data-placeholder="Selecionar">
                                    <option value=""></option>
                                    <?php foreach($produto as $value):?>
                                        <option value="<?php  echo $value['produto']?>"><?php  echo $value['produto']?></option>
                                    <?php endforeach;?>
								</select>
							</td>
							<td>
								<select name="desc1[]" class="form-control form-filter input-sm form-filter-consumidor" multiple="true" data-placeholder="Selecionar">
                                    <option value=""></option>
                                    <?php foreach($desc1 as $value):?>
                                        <option value="<?php  echo $value['desc1']?>"><?php  echo $value['desc1']?></option>
                                    <?php endforeach;?>
								</select>
							</td>
							<td>
								<select name="desc2[]" class="form-control form-filter input-sm form-filter-consumidor" multiple="true" data-placeholder="Selecionar">
                                    <option value=""></option>
                                    <?php foreach($desc2 as $value):?>
                                        <option value="<?php  echo $value['desc2']?>"><?php  echo $value['desc2']?></option>
                                    <?php endforeach;?>
								</select>
							</td>
							<td>
								<select name="desc3[]" class="form-control form-filter input-sm form-filter-consumidor" multiple="true">
                                    <option value=""></option>
                                    <?php foreach($desc3 as $value):?>
                                        <option value="<?php  echo $value['desc3']?>"><?php  echo $value['desc3']?></option>
                                    <?php endforeach;?>
								</select>
							</td>
							<td>
								<select name="desc4[]" class="form-control form-filter input-sm form-filter-consumidor" multiple="true" data-placeholder="Selecionar">
                                    <option value=""></option>
                                    <?php foreach($desc4 as $value):?>
                                        <option value="<?php  echo $value['desc4']?>"><?php  echo $value['desc4']?></option>
                                    <?php endforeach;?>
								</select>
							</td>
							<td>
								<select name="desc5[]" class="form-control form-filter input-sm form-filter-consumidor" multiple="true" data-placeholder="Selecionar">
                                    <option value=""></option>
                                    <?php foreach($desc5 as $value):?>
                                        <option value="<?php  echo $value['desc5']?>"><?php  echo $value['desc5']?></option>
                                    <?php endforeach;?>
								</select>
							</td>
						</tr>
						</thead>
						<tbody> </tbody>
					</table>
				</div>
			</div>
		</div>
		<!-- End: life time stats -->
	</div>
</div>

<script>

	function passaValorHidden(element1,element2){
	    element2.val(element1.val());
    }

	function showBuscaAvancada(){
	    if($('#busca-avancada').hasClass('hidden'))
            $('#busca-avancada').removeClass('hidden').fadeIn('slow');
		else
			$('#busca-avancada').fadeOut('slow').addClass('hidden');
    }

	function redirectConsumidores(){
		window.open('<?php echo $this->url('relatorio',array('action'=>'consumidor'))?>?'+$(':input.form-filter-pessoa').serialize()+'&'+$('select.form-filter-consumidor').serialize(),'_blank');

	}

	var TableDatatablesAjax = function () {

		var initPickers = function () {
			//init date pickers
			$('.date-picker').datepicker({
				rtl: App.isRTL(),
				autoclose: true
			});
		}

		var handleRecords = function () {

			var grid = new Datatable();

			grid.init({
				src: $("#datatable_ajax"),

				onSuccess: function (grid, response) {

					$('#manifestacoes-total').attr('data-value',response.recordsTotal);
					$('#manifestacoes-total').counterUp({time: 2500});

					$('#total-contatos').attr('data-value',response.totalContatos);
					$('#total-contatos').counterUp({time: 2500});

					$('#total-consumidores').attr('data-value',response.totalConsumidores);
					$('#total-consumidores').counterUp({time: 2500});
					// grid:        grid object
					// response:    json object of server side ajax response
					// execute some code after table records loaded
				},
				onError: function (grid) {
					// execute some code on network or other general error
				},
				onDataLoad: function(grid) {
					// execute some code on ajax data load
				},
				loadingMessage: 'Carregando...',
				dataTable: { // here you can define a typical datatable settings from http://datatables.net/usage/options

					// Uncomment below line("dom" parameter) to fix the dropdown overflow issue in the datatable cells. The default datatable layout
					// setup uses scrollable div(table-scrollable) with overflow:auto to enable vertical scroll(see: assets/global/scripts/datatable.js).
					// So when dropdowns used the scrollable div should be removed.
					//"dom": "<'row'<'col-md-8 col-sm-12'pli><'col-md-4 col-sm-12'<'table-group-actions pull-right'>>r>t<'row'<'col-md-8 col-sm-12'pli><'col-md-4 col-sm-12'>>",

					"bStateSave": true, // save datatable state(pagination, sort, etc) in cookie.
//                    paging: false,
                    searching: false,
					"lengthMenu": [
						[10, 20, 50, 100, 150],
						[10, 20, 50, 100, 150] // change per page values here
					],
					"pageLength": 10, // default record count per page
					"ajax": {
						"url": "<?php echo $this->basePath('relatorio/list-manifesto'); ?>", // ajax source
					},
					"order": [
						[1, "asc"]
					]// set first column as a default sort by asc
				}
			});

			// handle group actionsubmit button click
			grid.getTableWrapper().on('click', '.table-group-action-submit', function (e) {
				e.preventDefault();
				var action = $(".table-group-action-input", grid.getTableWrapper());
				if (action.val() != "" && grid.getSelectedRowsCount() > 0) {
					grid.setAjaxParam("customActionType", "group_action");
					grid.setAjaxParam("customActionName", action.val());
					grid.setAjaxParam("id", grid.getSelectedRows());
					grid.getDataTable().ajax.reload();
					grid.clearAjaxParams();
				} else if (action.val() == "") {
					App.alert({
						type: 'danger',
						icon: 'warning',
						message: 'Please select an action',
						container: grid.getTableWrapper(),
						place: 'prepend'
					});
				} else if (grid.getSelectedRowsCount() === 0) {
					App.alert({
						type: 'danger',
						icon: 'warning',
						message: 'No record selected',
						container: grid.getTableWrapper(),
						place: 'prepend'
					});
				}
			});
		}

		return {

			//main function to initiate the module
			init: function () {

				initPickers();
				handleRecords();
			}

		};

	}();

	jQuery(document).ready(function() {
		TableDatatablesAjax.init();
        $('select').chosen({
            no_results_text: "Oops, Não encontramos nada!"
    });
        $('select[name="datatable_ajax_length"').chosen('destroy');
	});

</script>

<style>
    .chosen-container{
        width:100% !important;
    }
</style>